 $(document).ready(function(){
            $("#bia").mouseover(function(){
              $("#biao3").hide()
              $("#biao5").show()
            })
            $("#bia").mouseout(function(){
              $("#biao3").show()
              $("#biao5").hide()
            })
          })
          $(document).ready(function(){
            $("#bia1").mouseover(function(){
              $("#biao4").hide()
              $("#biao6").show()
            })
            $("#bia1").mouseout(function(){
              $("#biao4").show()
              $("#biao6").hide()
            })
          })
          $(document).ready(function(){
            $("#biao7").mouseover(function(){
              $("#biao8").show()
            })
            $("#biao7").mouseout(function(){
              $("#biao8").hide()
            })
          })